### ISSUE TITLE
it duznt werk

### ISSUE THREAD

**Issue by drtshock** [mbax/PluginCatcher#4] opened 2013-04-20 01:56 UTC
^

**Comment by turt2live** [comment] 2013-04-20 01:57
cunfurmed

**Comment by natemort** [comment] 2013-04-20 02:00
+1

**Comment by SuperSpyTX** [comment] 2013-04-20 02:03
+9001

**Comment by mbax** [comment] 2013-04-20 02:08
oh
fixing

**Comment by drtshock** [comment] 2013-04-20 02:41
OMG YOU ROCK

**Comment by SuperSpyTX** [comment] 2013-04-20 04:22
YES IT WORKS AGAIN THANKS MBAX

**Comment by natemort** [comment] 2013-04-21 13:27
@mbax LATEST BUILD IS STILL BROKEN

**Comment by SuperSpyTX** [comment] 2013-04-21 13:40
@evilmidget38 NOOOO WHY YOU LIER

**Comment by SuperSpyTX** [comment] 2013-06-09 06:28
2 months and no fix.  y mbaxter.  y would u do dis.

**Comment by mbax** [comment] 2013-06-09 14:20
oops

**Comment by drtshock** [comment] 2013-06-09 17:03
stil not fix?

**Comment by SuperSpyTX** [comment] 2013-06-09 19:01
idk @evilmidget38 said latest build broken.

i tried latest build but it crashes every tiem

**Comment by turt2live** [comment] 2013-06-09 19:15
cunfirmd

i cnt get it 2 werk on my srver. 2 mny errs

**Comment by Iaccidentally** [comment] 2013-06-09 19:22
BUT THEN WHO WAS PHONE???

**Comment by davismariotti** [comment] 2013-06-09 19:23
Y U NO PUSH WRITE BUTTONS?!

**Comment by lol768** [comment] 2013-06-09 19:24
omg such trribl support - y u no reply in **FIVE HOURS**!?!?!?!?!

# imma find a better pluguin than this

**Comment by turt2live** [comment] 2013-06-09 19:33
hear is my err in my consoll

Java.MBAXFailedException (MainClassHere.java:88)
    at org.fail.mbaxter.everything.MainClass.java (MainClass.java:88)
    at org.fail.mbaxter.everything.AnotherClass.java (AnotherClass.java:88)
    at org.fail.mbaxter.everything.BukkitIsNotAtFault.java (BukkitIsNotAtFault.java:88)
    at org.fail.mbaxter.everything.Derp.java (Derp.java:88)
    at org.fail.mbaxter.everything.cats.everywhere.Portal.java (Portal.java:88)
Caused By: UnknownErrorException (YouFailed.java:99)
    at org.halp.no.error.SpamConsole.java (SpamConsole.java:254234)
    at org.dammit.internet.YouSuck.java (YouSuck.java:69)

**Comment by drtshock** [comment] 2013-06-09 19:39
I'm going to chargeback my $1000000 donation I made to you

**Comment by np98765** [comment] 2013-06-10 00:39
bump cuz this plugun sux and dosent wrk at all PLZ FIX KK?

**Comment by np98765** [comment] 2013-06-10 00:40
bump cuz its been 15 secods adn noone ansered meeee

**Comment by turt2live** [comment] 2013-06-10 00:42
omgeee this plugin has teh werst support evar

**Comment by davismariotti** [comment] 2013-06-10 01:12
ikr ^

**Comment by SuperSpyTX** [comment] 2013-06-10 01:59
dud lik i tired to run this on bungeecord serv and it duznt werk

mbax u no good codr i better and will writ bettr

**Comment by turt2live** [comment] 2013-06-10 02:01
this plugin is lting my plyrs dupe diamnds!

hlllpp!! I cnt let them duppe diamonds!!

**Comment by SuperSpyTX** [comment] 2013-06-10 02:03
@turt2live no no no!

i fix!

mbax y u lev a backdoor to nasa

**Comment by turt2live** [comment] 2013-06-10 02:03
iok, i try to fix 2

**Comment by Iaccidentally** [comment] 2013-06-10 02:04
how 2 plugin?

**Comment by mbax** [comment] 2013-06-10 06:17
Fixed with the power of my brain

#6 #7

**Closed as completed** 2013-06-10 06:17 UTC

**Comment by lol768** [comment] 2013-06-10 06:35
Yay :smile_cat:

**Comment by SuperSpyTX** [comment] 2013-06-10 10:14
MBAX Y U LIER THE PLUGIN CRASHED MY SERVER.

**Comment by SuperSpyTX** [comment] 2013-06-10 21:04
all gud i fixed it.
